name: SRPU-Model
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.26          
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=11.8
  - pandas
  - scikit-image
  - opencv
  - matplotlib
  - pip
  - pip:
      - albumentations
      - tqdm
      - wandb  
  - torchmetrics
  - tqdm
  - pillow
  - scikit-learn  
  - pip
  - pip:
    - albumentations  